/* Write your PL/SQL query statement below */

SELECT NAME, BALANCE
FROM (
    SELECT A.NAME, SUM(B.AMOUNT) AS BALANCE
    FROM USERS A
    JOIN TRANSACTIONS B ON A.ACCOUNT = B.ACCOUNT
    GROUP BY A.NAME
) A
WHERE BALANCE > 10000